name       : abiword
version    : 3.0.4
release    : 24
source     :
    - https://www.abisource.com/downloads/abiword/3.0.4/source/abiword-3.0.4.tar.gz : e93096cb192e5bc19d62e180fc5eda643206465315a710113ae5036bc2a1a5d7
homepage   : http://www.abisource.com/
license    : GPL-2.0-or-later
component  : office
summary    : Free lightweight word processor similar to Microsoft Word
description: |
    Abiword is a free and lightweight word processor similar to Microsoft Word, allowing many of the same functions while being better on resources.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(enchant)
    - pkgconfig(fribidi)
    - pkgconfig(gspell-1)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libturbojpeg)
    - pkgconfig(wv-1.0)
    - libboost-devel
    - libgcrypt-devel
    - intltool
clang      : no
libsplit   : no
setup      : |
    %configure --enable-emacs-keybinding \
             --enable-vi-keybinding \
             --enable-clipart \
             --enable-templates \
             --without-evolution-data-server \
             --with-goffice
build      : |
    %make
install    : |
    %make_install
