name       : abiword
version    : 3.0.2
release    : 12
source     :
    - http://www.abiword.org/downloads/abiword/3.0.2/source/abiword-3.0.2.tar.gz : afbfd458fd02989d8b0c6362ba8a4c14686d89666f54cfdb5501bd2090cf3522
homepage   : http://www.abisource.com/
license    : GPL-2.0
component  : office
summary    : Free lightweight word processor similar to Microsoft Word
description: |
    Abiword is a free and lightweight word processor similar to Microsoft Word, allowing many of the same functions while being better on resources.
builddeps  :
    - pkgconfig(fribidi)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(libpng)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pangocairo)
    - pkgconfig(wv-1.0)
    - libjpeg-turbo-devel
    - libgcrypt-devel
    - libboost-devel
    - intltool
clang      : no
libsplit   : no
setup      : |
    %patch -p1 < $pkgfiles/Fix-gtk-322-black-screen.patch
    %configure --enable-emacs-keybinding \
               --enable-vi-keybinding \
               --enable-clipart \
               --enable-templates \
               --enable-gio \
               --without-evolution-data-server \
               --with-goffice
build      : |
    %make
install    : |
    %make_install
