name       : abiword
version    : 3.0.2
release    : 22
source     :
    - https://github.com/AbiWord/abiword/archive/release-3.0.2.tar.gz : aa1c6f4400a376e2a85aa1869f924a58f2efc3c46ad2fbe798d8edba7ef4d5cf
homepage   : http://www.abisource.com/
license    : GPL-2.0-or-later
component  : office
summary    : Free lightweight word processor similar to Microsoft Word
description: |
    Abiword is a free and lightweight word processor similar to Microsoft Word, allowing many of the same functions while being better on resources.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(enchant)
    - pkgconfig(fribidi)
    - pkgconfig(gspell-1)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libturbojpeg)
    - pkgconfig(wv-1.0)
    - libboost-devel
    - libgcrypt-devel
    - intltool
clang      : no
libsplit   : no
setup      : |
    %patch -p1 < $pkgfiles/Fix-gtk-322-black-screen.patch
    %autogen --enable-emacs-keybinding \
             --enable-vi-keybinding \
             --enable-clipart \
             --enable-templates \
             --without-evolution-data-server \
             --with-goffice
build      : |
    %make
install    : |
    %make_install
