name        : abiword
version     : 3.0.1
release     : 5
source      :
    - http://www.abiword.org/downloads/abiword/3.0.1/source/abiword-3.0.1.tar.gz : e094f6fbf0afc5c5538b4894888e7c346f8ee8f49c9d24821dd696d0734865c6
homepage    : http://www.abisource.com/
license     :
    - GPLv2+
summary     : Free lightweight word processor similar to Microsoft Word
builddeps   :
    - pkgconfig(libpng)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libecal-1.2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(wv-1.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(fribidi)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libical)
    - libjpeg-turbo-devel
    - libgcrypt-devel
    - libboost-devel
    - intltool
clang       : no
libsplit    : no
description : |
    Abiword is a free and lightweight word processor similar to Microsoft Word, allowing many of the same functions while being better on resources.
setup      : |
    %configure --enable-emacs-keybinding \
               --enable-vi-keybinding \
               --enable-clipart \
               --enable-templates \
               --enable-gio \
               --with-evolution-data-server \
               --with-goffice
build      : |
    %make
install    : |
    %make_install
